# Generated by Django 2.2.5 on 2022-03-16 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220307_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='claenliness',
            new_name='cleanliness',
        ),
    ]
